refactor(wrapper): refactor conditions

diff --git a/rootfs/templates/wrapper b/rootfs/templates/wrapper
--- a/rootfs/templates/wrapper
+++ b/rootfs/templates/wrapper
@@ -84,51 +84,38 @@ function use() {
     # Implement DNS fix related to https://github.com/docker/docker/issues/24344
     DOCKER_ARGS+=("--dns=${DOCKER_DNS}")
   fi
-     
-  if [ -n "${HOME}" ]; then
-    if [ "${HOME}" == "/localhost" ]; then
-      echo "WARNING: not mounting ${HOME} because it conflicts with geodesic"
-    else
-      if  [[ $(cat /proc/version) =~ Microsoft ]] ; 
-      then
-        if [ -z "${LOCAL_HOME}" ]; 
-        then
-          windows_user_name=$(/mnt/c/Windows/System32/cmd.exe /c 'echo %USERNAME%' | tr -d '\r')
-          user_local_app_data=$(cmd.exe /c echo %LOCALAPPDATA% | tr -d '\r' | sed -e 's/\\/\//g')
 
+  if [ "${HOME}" == "/localhost" ]; then
+    echo "WARNING: not mounting ${HOME} because it conflicts with geodesic"
+  elif [ -n "${LOCAL_HOME}" ]; then
+    local_home=${LOCAL_HOME}
+  elif [[ $(cat /proc/version) =~ Microsoft ]]; then
+    windows_user_name=$(/mnt/c/Windows/System32/cmd.exe /c 'echo %USERNAME%' | tr -d '\r')
+    user_local_app_data=$(cmd.exe /c echo %LOCALAPPDATA% | tr -d '\r' | sed -e 's/\\/\//g')
 
-          if [ -d "/mnt/c/Users/${windows_user_name}/AppData/Local/lxss/" ]; 
-          then 
-            local_home=${user_local_app_data}/lxss${HOME}
-          else 
-            shopt -s nullglob
-            for dir in /mnt/c/Users/${windows_user_name}/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu* 
-            do
-              folder_name=$(basename ${dir})
-              local_home=${user_local_app_data}/Packages/${folder_name}/LocalState/rootfs${HOME}
-              break
-            done
-          fi
-        else
-          local_home=$LOCAL_HOME
-        fi
-
-        if [ -z "${local_home}" ]; 
-        then
-          echo "ERROR: can't identify user home directory, you may specify path via LOCAL_HOME variable"
-          exit 1;
-        else
-          echo Detected Windows Subsystem for Linux, mounting $local_home instead of $HOME
-        fi
-      else
-        local_home=${HOME}
-      fi
-
-
-      echo "# Mounting ${local_home} into container"
-      DOCKER_ARGS+=(--volume=${local_home}:/localhost)
+    if [ -d "/mnt/c/Users/${windows_user_name}/AppData/Local/lxss/" ]; then 
+      local_home=${user_local_app_data}/lxss${HOME}
+    else 
+      shopt -s nullglob
+      for dir in /mnt/c/Users/${windows_user_name}/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu* 
+      do
+        folder_name=$(basename ${dir})
+        local_home=${user_local_app_data}/Packages/${folder_name}/LocalState/rootfs${HOME}
+        break
+      done
     fi
+
+    if [ -z "${local_home}" ]; then
+      echo "ERROR: can't identify user home directory, you may specify path via LOCAL_HOME variable"
+      exit 1;
+    else
+      echo Detected Windows Subsystem for Linux, mounting $local_home instead of $HOME
+    fi
+    
   fi
+
+  echo "# Mounting ${local_home} into container"
+  DOCKER_ARGS+=(--volume=${local_home}:/localhost)
 
   DOCKER_ARGS+=(--privileged
                 --publish ${GEODESIC_PORT}:${GEODESIC_PORT}
