[wrapper, aws-vault] quickfixes (#415)
* [direnv, wrapper, aws-vault] quickfixes

diff --git a/rootfs/templates/wrapper b/rootfs/templates/wrapper
--- a/rootfs/templates/wrapper
+++ b/rootfs/templates/wrapper
@@ -139,7 +139,10 @@ function use() {
 		--name "${DOCKER_NAME}"
 		--rm
 		--env KUBERNETES_API_PORT=${GEODESIC_PORT})
-	set -o pipefail
+	# With set -o pipefail, the pipe below fails ~50% of the time on Mac due to a bug in bash.
+	# With set +o pipefail, this bug is mitigated, and the only difference is the behavior when `docker ps` fails.
+	# If `docker ps` fails, then it is likely that any further docker action will fail too, so it does not matter.
+	set +o pipefail
 	docker ps | grep -q ${DOCKER_NAME} >/dev/null 2>&1
 	if [ $? -eq 0 ]; then
 		echo "# Attaching to existing ${DOCKER_NAME} session"
