Attemt to Sync System Time with Hardware Clock (#4)

diff --git a/dist/profile b/dist/profile
--- a/dist/profile
+++ b/dist/profile
@@ -1,12 +1,21 @@
 #!/bin/bash
 
 if [ "${BOOTSTRAP}" == "true" ]; then
+  # Output the bootstrap script
   stty -onlcr
   cat contrib/geodesic
   exit 0
 fi
 
 echo "Entering the geodesic shell..."
+
+# Sync Docker VM's hardware clock which can drift when host machine sleeps
+#   e.g. An error occurred (SignatureDoesNotMatch) when calling the AssumeRole operation: 
+#        Signature expired: 20170103T233357Z is now earlier than 20170104T042623Z (20170104T044123Z - 15 min.)
+hwclock -s 2>/dev/null
+if [ $? -ne 0 ]; then
+  echo "Warning: unable to sync system time from hardware clock; you may encounter problems with signed requests as a result of time drift."
+fi
 
 # Create directories
 mkdir -p $(dirname ${TF_STATE_FILE})
