working remote configs and modules

diff --git a/modules/hub/Makefile b/modules/hub/Makefile
--- a/modules/hub/Makefile
+++ b/modules/hub/Makefile
@@ -7,19 +7,28 @@ MESSAGE ?= "Automatic commit"
 validate:
 	$(call assert-set,CLUSTER_NAME)
 
-## Create a new cluster repo
+## Create a new private cluster repo
 create: validate test
 	@[ -d $(CLUSTER_REPO_PATH) ] || mkdir -p $(CLUSTER_REPO_PATH)
 	@[ -d $(CLUSTER_REPO_PATH)/.git ] || git -C $(CLUSTER_REPO_PATH) init
-	@hub -C $(CLUSTER_REPO_PATH) create
+	@cd $(CLUSTER_REPO_PATH) && \
+		hub create -p -d "Geodesic cluster configuration for $(CLUSTER_NAME)" $(GITHUB_ORG)/$(CLUSTER_NAME) 
 
 ## Clone an existing cluster repo
 clone: validate test
 	@git -C $(CLUSTER_REPO_PATH) clone 
-	@cloud hub update
+	@cloud hub pull
+
+## Update local cluster repo 
+update:
+	if [ -d "$(CLUSTER_REPO_PATH)" ]; then \
+		cloud hub pull; \
+	else \
+		cloud hub clone; \
+	fi
 
 ## Pull down updates
-update: validate test
+pull: validate test
 	@git -C $(CLUSTER_REPO_PATH) pull origin
 	@git -C $(CLUSTER_REPO_PATH) submodule update --init --remote
 
@@ -38,5 +47,5 @@ status:
 ## Test github connection
 test:
 	@set -o pipefail;  \
-	(ssh  -o StrictHostKeyChecking=no git@github.com 2>&1 | grep 'successfully authenticated' | cut -d' ' -f2 | cut -d'!' -f1) || \
-	(echo "Failed to authetnicate with github. Make sure your SSH keys have been added to your agent."; exit 1)
+	 GITHUB_USERNAME=$$(ssh  -o StrictHostKeyChecking=no git@github.com 2>&1 | grep 'successfully authenticated' | cut -d' ' -f2 | cut -d'!' -f1); \
+	[ -n "$$GITHUB_USERNAME" ] || (echo "Failed to authetnicate with github. Make sure your SSH keys have been added to your agent."; exit 1)
