[shfmt] format all bash scripts and lint check on CI (#305)
* feat(*): add target for shfmt, format scripts

* style(*): format scripts

* feat(*): change fmt targets

Now fmt fails when some files not formatted
Fix wrapper and bootstrap - fmt can't process gomplate

* feat(travis): add fmt check to CI

diff --git a/rootfs/usr/local/bin/confirm b/rootfs/usr/local/bin/confirm
--- a/rootfs/usr/local/bin/confirm
+++ b/rootfs/usr/local/bin/confirm
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 if [ $# -lt 1 ]; then
-  echo "usage: $0 [env] [msg]"
-  exit 1
+	echo "usage: $0 [env] [msg]"
+	exit 1
 fi
 
 sigint() {
-  echo -e "\nAborted"
-  exit 1
+	echo -e "\nAborted"
+	exit 1
 }
 
 trap sigint SIGINT
@@ -16,9 +16,9 @@ ASSERT_ENV=$1
 ASSERT_MSG=${2:-Are you sure you wish to modify \"${!ASSERT_ENV}\"?}
 
 echo "${ASSERT_MSG}"
-until [[ ${CONFIRMATION} == ${!ASSERT_ENV} ]]; do 
-  echo "Enter \"${!ASSERT_ENV}\" to continue, or ^C to abort"
-  echo -n "> ";
-  read CONFIRMATION
+until [[ ${CONFIRMATION} == ${!ASSERT_ENV} ]]; do
+	echo "Enter \"${!ASSERT_ENV}\" to continue, or ^C to abort"
+	echo -n "> "
+	read CONFIRMATION
 done
 echo "Confirmed"
