Geodesic version 3 (#945)

diff --git a/rootfs/usr/local/bin/docs b/rootfs/usr/local/bin/docs
--- a/rootfs/usr/local/bin/docs
+++ b/rootfs/usr/local/bin/docs
@@ -1,77 +1,71 @@
-#!/usr/bin/variant1
-# vim:set ft=yaml
+#!/bin/bash
 
-mixins:
-  # Exit on all errors
-  exit_on_errors: &exit_on_errors
-    set -e
+_docs_build() {
+  if ! command -v pandoc >/dev/null; then
+    tput setaf 1; echo "Cannot build docs: pandoc is not installed. Please install it first." >&2; tput sgr0
+    exit 1
+  fi
+	section=1
+	man_pages=/usr/share/man/man${section}
+	mkdir -p ${man_pages}
+	for md in $(find /usr/share/docs -type f -name '*.md'); do
+		man=${man_pages}/$(basename $md .md).$section
+		# Verbatim text (i.e. between backticks, `…`) doesn’t show in any particular way, so we bold it
+		# by using "**", but we need to preserve code fence triple backticks "```".
+		# We also need to disable latex_macros and tex_math_dollars because they can be
+		# accidentally triggered by dollar signs.
+		sed 's/```/~#~#/g' <$md | sed 's/`/**/g' | sed -E 's/^#(#+ )/\1/g' | sed 's/~#~#/```/g' |
+			pandoc -s -f markdown-latex_macros-tex_math_dollars --variable=hyphenate:false -t man | sed 's/\\\[en\]/-/' >$man
+		echo "Wrote $man"
+	done
+}
 
-  # Default runner
-  runner: &runner
-    command: "bash"
-    args: ["-ex", "-c"]
+_docs_index() {
+	mandb -c
+}
 
-tasks:
-  update:
-    description: "Rebuild man pages and reindex"
-    steps:
-    - task: "build"
-    - task: "index"
+_docs_list() {
+	echo -e "Available topics:\n"
+	apropos . | sed 's/^/  /'
+	echo
+}
 
-  build:
-    # Build man pages
-    description: "Build man pages"
-    script:
-    - *exit_on_errors
-    - |
-      section=1
-      man_pages=/usr/share/man/man${section}
-      mkdir -p ${man_pages}
-      for md in $(find /usr/share/docs -type f -name '*.md'); do
-        man=${man_pages}/$(basename $md .md).$section
-        # Verbatim text (i.e. between backticks, `…`) doesn’t show in any particular way, so we bold it
-        # by using "**", but we need to preserve code fence triple backticks "```".
-        # We also need to disable latex_macros and tex_math_dollars because they can be
-        # accidentally triggered by dollar signs.
-        sed 's/```/~#~#/g' < $md | sed 's/`/**/g' | sed -E 's/^#(#+ )/\1/g' | sed 's/~#~#/```/g' | \
-          pandoc -s -f markdown-latex_macros-tex_math_dollars --variable=hyphenate:false -t man | sed 's/\\\[en\]/-/' > $man
-        echo "Wrote $man"
-      done
+_docs_search() {
+	topic=$(apropos . | awk '{print $1}' | fzf \
+		--height 50% \
+		--preview-window right:70% \
+		--reverse \
+		--select-1 \
+		--prompt='-> ' \
+		--header 'Select Help Topic' \
+		--query "${1}" \
+		--preview "man {} | head -20")
 
-  index:
-    description: "Index man pages"
-    script:
-    - *exit_on_errors
-    - mandb -c
+	if [ -n "${topic}" ]; then
+		man $topic
+	fi
+}
 
-  list:
-    description: "List all available man pages"
-    script:
-    - *exit_on_errors
-    - echo -e "Available topics:\n"
-    - apropos . | sed 's/^/  /'
-    - echo
-
-  search:
-    description: "Search documentation"
-    interactive: true
-    parameters:
-    - name: query
-      type: string
-      default: ""
-      description: "Search query"
-      required: false
-    script: |-
-      topic=$(apropos . | awk '{print $1}' | fzf \
-        --height 50% \
-        --preview-window right:70% \
-        --reverse \
-        --select-1 \
-        --prompt='-> ' \
-        --header 'Select Help Topic' \
-        --query "${1}" \
-        --preview "man {} | head -20")
-
-      if [ -n "${topic}" ]; then
-        man $topic
-      fi
+set -e
+case $1 in
+update)
+	_docs_build
+	_docs_index
+	;;
+build)
+	_docs_build
+	;;
+index)
+	_docs_index
+	;;
+list)
+	_docs_list
+	;;
+search)
+	_docs_search "${@:2}"
+	;;
+*)
+	echo "Usage: $0 {list|search|build|index|update}"
+	exit 1
+	;;
+esac
