Security updates, better EKS cluster support

diff --git a/rootfs/usr/local/bin/eks-update-kubeconfig b/rootfs/usr/local/bin/eks-update-kubeconfig
--- a/rootfs/usr/local/bin/eks-update-kubeconfig
+++ b/rootfs/usr/local/bin/eks-update-kubeconfig
@@ -22,15 +22,15 @@ Usage:
   With "off", deletes the currently active kubecfg file.
 
   NOTE: This tool assumes you are using Cloud Posse's standard naming conventions:
-  * Cluster name "corp" expands to "${NAMESPACE}-corp-eks-cluster"
-  * Role name "admin" expands to "${NAMESPACE}-corp-admin"
+  * Cluster name "uw2-corp" expands to "${NAMESPACE}-uw2-corp-eks-cluster"
+  * Role name "admin" expands to "${NAMESPACE}-gbl-corp-admin"
 
 EOF
 }
 
 function profile_name() {
 	local profile_arg="${2:-${ASSUME_ROLE}}"
-	printf "%s" "${NAMESPACE:+${NAMESPACE}-}${1}-${profile_arg##*-}"
+	printf "%s" "${NAMESPACE}-gbl-${1#*-}-${profile_arg##*-}"
 }
 
 function file_name() {
@@ -45,6 +45,10 @@ function red() {
 }
 
 main() {
+	if [[ -z $NAMESPACE ]]; then
+	  printf "%s: %s\n\n" "$(basename $0)" "$(red Environment variable NAMESPACE is required but not set)"  >&2
+	  return 9
+	fi
 	if (($# == 0)); then
 		usage
 		return 1
@@ -59,18 +63,32 @@ main() {
 		fi
 		return 0
 	fi
-	if [[ -z ${ASSUME_ROLE:-$2} ]]; then
-		printf "%s: %s\n\n" "$(basename $0)" "$(red "* No role specified and \$ASSUME_ROLE unset. Giving up.")" >&2
+	local role
+	if [[ $1 == "set-kubeconfig" ]]; then
+		role="$3"
+	else
+		role="$2"
+	fi
+	if [[ -z $role ]]; then
+		role="$ASSUME_ROLE"
+		if [[ $role =~ identity$ ]]; then
+			role=$(aws sts get-caller-identity --output text --query 'Arn' | cut -d/ -f2)
+		fi
+	fi
+	if [[ -z ${role} ]]; then
+		printf "%s: %s\n\n" "$(basename $0)" "$(red "* No role specified and cannot guess role. Giving up.")" >&2
 		usage
 		return 9
 	fi
 	if [[ $1 == "set-kubeconfig" ]]; then
-		file_name $2 $3
+		file_name $2 $role
 		return 0
 	fi
 
+	local kubecfg="$(file_name $1 $role)"
 	EKS_CLUSTER_NAME_PATTERN="${EKS_CLUSTER_NAME_PATTERN:-${NAMESPACE:+${NAMESPACE}-}%s-eks-cluster}"
-	aws --profile $(profile_name $1 $2) eks update-kubeconfig --name=$(printf "$EKS_CLUSTER_NAME_PATTERN" $1) --kubeconfig="$(file_name $1 $2)"
+	aws --profile $(profile_name $1 $role) eks update-kubeconfig --name=$(printf "$EKS_CLUSTER_NAME_PATTERN" $1) --kubeconfig="$kubecfg" && \
+	chmod 600 "$kubecfg"
 }
 
 main "$@"
