General Updates for Pilot (#6)
* Reduce validation on ssh

* init helm

* ssh key rotation and default ssh config

* Use KOPS_STATE_STORE

* Upgrade kops. drop --name argument.

* fix paths, push state

* Increase master node size

* Add aliases. Clean up whitespace

* Add proxy support

* Update docs

* confirm destructive actions

* Add known hosts file support

* fix whitespace

* make it easy to switch between clusters

* Use git commits to make versioning easier

* Add optimistic locking

* initialize git

* call heapster monitoring

* Add ssh key if not already added; use privileged by default so we can set hardware clock

* Update README

* Add install.sh

* support multiple sessions in the same shell

* Simplify installation

* clean up langauge

* Fix watch output

diff --git a/dist/contrib/geodesic b/dist/contrib/geodesic
--- a/dist/contrib/geodesic
+++ b/dist/contrib/geodesic
@@ -1,13 +1,20 @@
 #!/bin/bash
 # Please run the following commands to start the geodesic shell (modify as necessary)
 DOCKER_IMAGE=${DOCKER_IMAGE:-cloudposse/geodesic}
-DOCKER_TAG=${DOCKER_TAG:-dev}
+DOCKER_TAG=${DOCKER_TAG:-latest}
+DOCKER_NAME=${DOCKER_NAME:-geodesic}
 STATE_DIR=${STATE_DIR:-${HOME}/.geodesic}
 OS=$(uname -s)
 mkdir -p ${STATE_DIR}
+
+if ! which docker > /dev/null; then
+  echo "Cannot find docker installed on this system. Please install and try again."
+  exit 1
+fi
+
 if [ -t 1 ]; then
   # Running in terminal 
-  DOCKER_ARGS=(-it --env LS_COLORS --env TERM --env TERM_COLOR)
+  DOCKER_ARGS=(-it --rm --name="${DOCKER_NAME}-bootstrap" --env LS_COLORS --env TERM --env TERM_COLOR)
 
   if [ -n "$SSH_AUTH_SOCK" ]; then
     if [ `uname -s` == 'Darwin' ]; then
@@ -32,14 +39,26 @@ if [ "${OS}" == "Darwin" ]; then
   # Run in privleged mode to enable time synchronization of system clock with hardware clock
   # Implement DNS fix related to https://github.com/docker/docker/issues/24344
   DOCKER_ARGS=("${DOCKER_ARGS[@]}"
-                --privileged
                 --dns=8.8.8.8
               )
 fi
 
 DOCKER_ARGS=("${DOCKER_ARGS[@]}"
+              --privileged
+              --publish 8001:8001
+              --name "${DOCKER_NAME}"
               --rm 
               --env BOOTSTRAP=false
               --volume ${STATE_DIR}:/geodesic/state)
 
-docker run "${DOCKER_ARGS[@]}" ${DOCKER_IMAGE}:${DOCKER_TAG} $*
+docker inspect geodesic >/dev/null 2>&1
+if [ $? -eq 0 ]; then
+  echo "# Attaching to existing ${DOCKER_NAME} session"
+  if [ $# -eq 0 ]; then
+    set -- "/bin/bash" "--rcfile" "/geodesic/profile" "$@"
+  fi
+  docker exec -it "${DOCKER_NAME}" $*
+else
+  echo "# Starting new ${DOCKER_NAME} session"
+  docker run "${DOCKER_ARGS[@]}" ${DOCKER_IMAGE}:${DOCKER_TAG} $*
+fi
