Add ssh key if not already added; use privileged by default so we can set hardware clock

diff --git a/dist/contrib/geodesic b/dist/contrib/geodesic
--- a/dist/contrib/geodesic
+++ b/dist/contrib/geodesic
@@ -1,10 +1,16 @@
 #!/bin/bash
 # Please run the following commands to start the geodesic shell (modify as necessary)
 DOCKER_IMAGE=${DOCKER_IMAGE:-cloudposse/geodesic}
-DOCKER_TAG=${DOCKER_TAG:-dev}
+DOCKER_TAG=${DOCKER_TAG:-latest}
 STATE_DIR=${STATE_DIR:-${HOME}/.geodesic}
 OS=$(uname -s)
 mkdir -p ${STATE_DIR}
+
+if ! which docker > /dev/null; then
+  echo "Cannot find docker installed on this system. Please install and try again."
+  exit 1
+fi
+
 if [ -t 1 ]; then
   # Running in terminal 
   DOCKER_ARGS=(-it --env LS_COLORS --env TERM --env TERM_COLOR)
@@ -32,13 +38,13 @@ if [ "${OS}" == "Darwin" ]; then
   # Run in privleged mode to enable time synchronization of system clock with hardware clock
   # Implement DNS fix related to https://github.com/docker/docker/issues/24344
   DOCKER_ARGS=("${DOCKER_ARGS[@]}"
-                --privileged
-                --publish 8001:8001
                 --dns=8.8.8.8
               )
 fi
 
 DOCKER_ARGS=("${DOCKER_ARGS[@]}"
+              --privileged
+              --publish 8001:8001
               --rm 
               --env BOOTSTRAP=false
               --volume ${STATE_DIR}:/geodesic/state)
