reset local state

diff --git a/modules/kops/Makefile b/modules/kops/Makefile
--- a/modules/kops/Makefile
+++ b/modules/kops/Makefile
@@ -131,13 +131,17 @@ rotate-ssh-key: delete-ssh-key create-ssh-key configure-ssh-key apply wait-until
 
 ## Add ssh key to agent
 add-ssh-key:
-	@if ssh-add -l | grep -q "$$(ssh-keygen -lf "$${KOPS_STATE_PATH}/id_rsa" | awk '{print $$2}')"; then \
-		echo "SSH key already added to agent"; \
+	@if [ -f "$${KOPS_STATE_PATH}/id_rsa" ]; then \
+		if ssh-add -l | grep -q "$$(ssh-keygen -lf "$${KOPS_STATE_PATH}/id_rsa" | awk '{print $$2}')"; then \
+			echo "SSH key already added to agent"; \
+		else \
+		    chmod 600 "$${KOPS_STATE_PATH}/id_rsa"; \
+			ssh-add "$${KOPS_STATE_PATH}/id_rsa"; \
+		fi; \
 	else \
-	  ssh-add "$${KOPS_STATE_PATH}/id_rsa"; \
+		echo "Cannot find SSH key: $${KOPS_STATE_PATH}/id_rsa"; \
+		exit 1; \
 	fi
-
-
 
 ## List secrets
 describe-secrets:
